# Method 1

SELECT EMAIL FROM (SELECT EMAIL, COUNT(EMAIL) AS NUM FROM PERSON GROUP BY EMAIL) AS STATISTICS WHERE NUM > 1;


# Method 2

SELECT EMAIL FROM PERSON GROUP BY EMAIL HAVING COUNT(EMAIL) > 1;
